apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: spinning
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  nodePath: /mnt/spinning
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mirrored
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  nodePath: /mnt/mirrored
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  nodePath: /mnt/fast
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fixed
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  nodePath: /mnt/fixed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["/var/lib/rancher/k3s/storage"]
        },
        {
          "node": "redtrim",
          "paths": ["/mnt/spinning", "/mnt/mirrored", "/mnt/fast", "/mnt/fixed"]
        }
      ]
    }
